### ISSUE TITLE
Trouble finding the right exe version to patch

### ISSUE THREAD

**Issue by AlmeidaRW** [PARTYMANX/partymod-thaw#4]
Hi,

I have been scouring the internet for the correct version of the exe file, to no avail. I found 4 different versions of THAW.exe floating online, with the following CRC as reported by partypatcher.exe:

67741c1c
bc1b2c8b
aee86f12
ac38c39a

Looking at the following code snippet
https://github.com/PARTYMANX/partymod-thaw/blob/118aca8027b426f34f7010d17c4686c850a41c41/patcher/main.c#L47

It's clear that the application is expecting either a8290acf or ae1cc8f3. Can you give me and anyone who stumbles across this in the future a more specific pointer on where to get the executable your patch expects?

Thanks!

**Comment by PARTYMANX** [comment]
The patcher console output is pretty bad at the moment.  If there's an unexpected checksum, it will still apply the patch unless the executable is of a different size (which seems like it should be safe but i'm not sure what releases are out there).  If there is an output CRC listed, the patch was potentially applied.

I can't point to specifics, but I know at least one of the executables I've used were pre-patched for online play (pointing to openspy instead of gamespy, for one thing).  One was much smaller than the other.

**Comment by AlmeidaRW** [comment]
Thanks for the quick reply. The patch was indeed applied, as all 4 variants I posted about above are of the sizes stipulated in the patcher's source code. One of them was indeed patched to OpenSpy. I was really hoping to get this working on my Steam Deck, I have been meaning to make it the ultimate THPS machine.

Does this executable of yours, the small one, require a CD for the game to be played?

Thanks again!

**Comment by PARTYMANX** [comment]
Okay, that's good.  If the game is launching from `THAWPM.exe`, it should be all good... I think.  To be honest I never actually tried to see what it does when given an entirely invalid executable.  In theory it should try writing to `NULL` which will cause an immediate crash (I should probably just make it explicitly fail the DLL main...).  If it responds to partyconfig changes or spawns a console window on startup, those are sure signs.  I've been playing on my Steam Deck as well, so that should work well.

The smaller executable I mentioned does not require a CD.  The disc version of the game is not currently supported due to the details of its DRM not being compatible with my current design (namely, the full executable, including its import table, is encrypted.  the current plan is to provide a workaround hooked DLL for either directinput, directx, or bink video, then have that load partymod's dll when needed).  I have an idea for a workaround, but it's pretty low priority because from what I can tell, the original discs for this game are rather rare and relatively few people even own a drive in 2023.  Bit of a tangent, but it was on my mind recently.

**Comment by AlmeidaRW** [comment]
That's the thing, the game did not work from THAWPM.exe under any of the scenarios I described. Whether it was due to my Lutris settings or the incorrect exe, I don't know. I did try your mod for thps3 and also can't get it to work, but the vanilla game also doesn't boot.

At least now I know you have THAW running on a Steam Deck, so it is possible.

**Comment by PARTYMANX** [comment]
3 needs `NoMovie` in the ini set to `1` to run on the Deck (i have mine working on Proton 7.0-6).  for some reason movie playback just doesn't work.

I don't think I needed anything special for THAW to work, but I always work within steam itself and not lutris, so I can't quite say if the executables aren't working with the patch or what.

**Comment by PARTYMANX** [comment]
Corrected a bug in 0.10.1 that was preventing startup on Linux (egg on my face).  Also added additional checksums to the patcher.  Fixes are available in 0.11.0.
